# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18WBeMscnI0dbw9Kw3I1ucpHXuO0mDb7T
"""

import tweepy
from textblob import TextBlob
from wordcloud import WordCloud
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import csv
plt.style.use('fivethirtyeight')
consumerKey = "xxxxxxxxxxxxxxxxxxx"
consumerSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
accessToken = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
accessTokenSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
def cleanTxt(text):
  text = re.sub('@[A-Za-z0-9]+','',text)
  text = re.sub('#','',text)
  text = re.sub('RT[\s]+','',text)
  text = re.sub('http?:\/\/\S+','',text)
  return (text)
def Subjectivecontent(text):
  return TextBlob(text).sentiment.subjectivity
def Polaritycontent(text):
  return TextBlob(text).sentiment.polarity
def getAnalysis(score):
  if score < 0 :
    return 'Negative'
  elif score == 0 :
    return 'Neutral'
  else :
    return 'Positive'

authenticate = tweepy.OAuthHandler(consumerKey, consumerSecret) 
authenticate.set_access_token(accessToken, accessTokenSecret) 
api = tweepy.API(authenticate, wait_on_rate_limit = True)
posts = api.search(q = input("Enter the hashtag please"), count = 100, lang ="en", tweet_mode="extended")

#  Print the last 5 tweets
#print("Show the 5 recent tweets:\n")
i=1
#for tweet in posts[:5]:
   #print(str(i) +') '+ tweet.full_text + '\n')
   #i= i+1
#print(posts)
df = pd.DataFrame([tweet.full_text for tweet in posts], columns=['Tweets'])
# Show the first 5 rows of data

df.drop_duplicates(["Tweets"])
#df.head()
df['Tweets'] = df['Tweets'].str.rstrip()
df['Tweets'] = df['Tweets'].apply(cleanTxt)
# subjectivity of tweets
df['subject'] = df['Tweets'].apply(Subjectivecontent)
# polarity of tweets
df['polarity_tweet'] = df['Tweets'].apply(Polaritycontent)
# Analysing Tweets
df['Analysis'] = df['polarity_tweet'].apply(getAnalysis)
#df.head()
#Visualization bash board
positweets = df[df.Analysis == 'Positive']
positweets = positweets['Tweets']
positweetspercent = round((positweets.shape[0]/df.shape[0])*100,1)
#positweetspercent
negatitweets = df[df.Analysis == 'Negative']
negatitweets = negatitweets['Tweets']
negatitweetspercent = round((negatitweets.shape[0]/df.shape[0])*100,1)

neutraltweets = df[df.Analysis == 'Neutral']
neutraltweets = neutraltweets['Tweets']
neutraltweetspercent = round((neutraltweets.shape[0]/df.shape[0])*100,1)

#df['Analysis'].value_counts()

plt.title('SENTIMENT ANALYSIS DASHBOARD')
#df['Analysis'].value_counts().plot(kind = 'pie')
plt.xlabel('Polarity')
plt.ylabel('Percent')
df['Analysis'].value_counts().plot(kind = 'bar')
plt.show()